config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: redirect('/api-docs')
  # root "users#index"
  # get "/users", to: "users#index"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :doctors, only: [:index, :show, :create, :update, :destroy]
      resources :reservations, only: [:index, :show, :create, :update, :destroy]
      post '/login', to: 'authentication#login'
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations

  validates :name, presence: true
  validates :image_url, presence: true
  validates :doctor_type, presence: true
  validates :address, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :doctor

  validates :date_of_reservation, presence: true
  validates :city, presence: true
  validates :doctor_id, presence: true
  validates :user_id, presence: true

 def doctor_name
    doctor&.name
  end

  def user_name
    user&.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :doctors, through: :reservations

  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/authentication_controller.rb
class Api::V1::AuthenticationController < ApplicationController
  skip_before_action :verify_authenticity_token
  def login
    user = User.find_by(name: params[:name])

    if user 
      token = user.generate_jwt
      render json: { user_id: user.id, name: user.name, token: token }, status: :created
    else
      head :unauthorized
    end
  end
end

app/controllers/api/v1/doctors_controller.rb
class Api::V1::DoctorsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_doctor, only: %i[show edit update destroy]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show; end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit; end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to api_v1_doctor_path(@doctor), notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to api_v1_doctor_path(@doctor), notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy!

    respond_to do |format|
      format.html { redirect_to api_v1_doctors_path, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def doctor_params
    params.require(:doctor).permit(:name, :doctor_type, :description, :image_url, :book_price, :book_date)
  end
end

app/controllers/api/v1/reservations_controller.rb
class Api::V1::ReservationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_reservation, only: %i[show edit update destroy]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show; end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit; end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to api_v1_reservations_path(@reservation), notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to api_v1_reservations_path(@reservation), notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy!

    respond_to do |format|
      format.html { redirect_to api_v1_reservations_path, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def reservation_params
    params.require(:reservation).permit(:city, :duration_of_booking, :date_of_reservation, :doctor_id, :user_id)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def create
    @user = User.new(user_params)

    if @user.save
      token = @user.generate_jwt
      render json: { token: }, status: :created
    else
      render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authorize_request
    header = request.headers['Authorization']
    header = header.split.last if header

    begin
      @decoded = JWT.decode(header, Rails.application.secret_key_base)[0]
      @current_user = User.find(@decoded['id'])
    rescue JWT::DecodeError
      head :unauthorized
    end
  end
end

app/helpers/api/v1/authentication_helper.rb
module Api::V1::AuthenticationHelper
end

app/helpers/api/v1/doctors_helper.rb
module Api::V1::DoctorsHelper
end

app/helpers/api/v1/reservations_helper.rb
module Api::V1::ReservationsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <p>
    <strong>Name:</strong>
    <%= doctor.name %>
  </p>

  <p>
    <strong>Doctor-type:</strong>
    <%= doctor.doctor-type %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= doctor.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= doctor.image_url %>
  </p>

  <p>
    <strong>Book price:</strong>
    <%= doctor.book_price %>
  </p>

  <p>
    <strong>Book-date:</strong>
    <%= doctor.book-date %>
  </p>

</div>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :doctor-type, style: "display: block" %>
    <%= form.text_field :doctor-type %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :book_price, style: "display: block" %>
    <%= form.text_field :book_price %>
  </div>

  <div>
    <%= form.label :book-date, style: "display: block" %>
    <%= form.date_field :book-date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Doctors</h1>

<div id="doctors">
  <% @doctors.each do |doctor| %>
    <%= render doctor %>
    <p>
      <%= link_to "Show this doctor", doctor %>
    </p>
  <% end %>
</div>

<%= link_to "New doctor", new_doctor_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalCapstoneBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>